package com.example.demo.common.xmlutil;

import lombok.Data;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
@Data
public class Me {

  private String objectid;
  private String idonems;
  private String emsname;
  private String meid;
  private String mename;
  private String metype;
  private String vendor;
  private String juzhanobjectid;
  private String jifangobjectid;
  private String rackobjectid;
  private String shelfnumber;
  private String userlabel;
  private String transportlayerrates;
  private String model;
  private String hardwareversion;
  private String softwareversion;
  private String servicestate;
  private String maxtransportlayerrate;
  private String creator;
  private String communicationaddress;
  private String telephone;
  private java.sql.Date createtime;
  private String xoffset;
  private String yoffset;
  private String additionalinfo;
  private String preconfig;
  private String servicelevel;
  private String transmitmode;
  private String gateway;
  private String emsobjectid;
  private String wavechannelnumber;
  private double maxoutputpower;
  private String istddevice;
  private Date maintenancetime;
  private String plane;
  private String nativeemsname;
  private String maintenanceuser;
  private String parentmeobjectid;
  private String isvirtualme;
  private String isimportantme;
  private String isinterconnectme;
  private String othercorporation;
  private String operatinostate;
  private String managementip;
  private String serviceip;
  private String nmsmename;
  private String assetnumber;
  private String projectname;
  private String submitmaintenancestate;
  private java.sql.Date submitmaintenancedate;
  private java.sql.Date initialcheckdate;
  private java.sql.Date finalcheckdate;
  private String maintainanceperiod;
  private String nonwarranty;
  private String mepower;
  private String maintainancepattern;
  private String clockinfo;
  private String powersupplyway;
  private String powermodel;
  private String powerassetnumber;
  private String property;
  private String powertype;
  private String batterycapacity;
  private String servicevendor;
  private String equipmentstatu;
  private String belonggrid;
  private String maintainvendor;
  private String planname;
  private String planno;
  private String location;
  private String communicationstate;
  private String megrade;
  private String synchroservicevendor;
  private String isltevirtualme;
  private String importance;
  private String managementdomain;
  private String toposubnetworkname;
  private String ispowerandjifangpoorpoint;
  private String netstate;
  private String maintenanceperson;
  private String ratedpower;
  private String controlplaneip;
  private String availablestate;
  private String netype;
  private java.sql.Date updatetime;
  private String objectkey;
  private String irmsmeobjectid;
  private String team;
  private String strongholdid;
  private String managementlocked;
  private String alarmdomain;
  private String masterboardserialnumber;
  private String macaddress;
  private String devicepurpose;
  private String omccreatetime;
  private String remark;
  private String physicalrole;
  private String isgateway;

}
